# Generated by Django 5.0.6 on 2024-05-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Archivo', models.FileField(upload_to='construred/archivos/')),
                ('Proyecto', models.ForeignKey(db_column='idProyecto', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
        ),
    ]
