# Generated by Django 5.0.6 on 2024-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '__first__'),
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.ForeignKey(db_column='idEquipo', on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
                ('Proyecto', models.ForeignKey(db_column='idProyecto', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
        ),
    ]
