# Generated by Django 5.0.6 on 2024-05-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHoraInicio', models.DateTimeField()),
                ('FechaHoraFinal', models.DateTimeField()),
                ('Motivo', models.TextField()),
                ('Equipo', models.ForeignKey(db_column='idEquipo', on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
            ],
        ),
    ]
