# Generated by Django 5.0.6 on 2024-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
