# Generated by Django 5.0.6 on 2024-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Equipo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
                ('Equipo', models.ForeignKey(db_column='idEquipo', on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
            ],
        ),
    ]
