# Generated by Django 5.0.6 on 2024-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=20, unique=True)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=50, unique=True)),
                ('Contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
