# Generated by Django 5.0.6 on 2024-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '__first__'),
        ('Contrato', '__first__'),
        ('MetodoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MontoCliente', models.DecimalField(decimal_places=2, max_digits=9)),
                ('FechaPago', models.DateField()),
                ('Factura', models.FileField(upload_to='construred/factura/')),
                ('Cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('Contrato', models.ForeignKey(db_column='idContrato', on_delete=django.db.models.deletion.CASCADE, to='Contrato.contrato')),
                ('MetodoPago', models.ForeignKey(db_column='idMetodoPago', on_delete=django.db.models.deletion.CASCADE, to='MetodoPago.metodopago')),
            ],
        ),
    ]
