# Generated by Django 5.0.6 on 2024-05-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarea', models.TextField()),
                ('FechaHora', models.DateTimeField()),
                ('Estado', models.CharField(default='Pendiente', max_length=50)),
                ('Agenda', models.ForeignKey(db_column='idAgenda', on_delete=django.db.models.deletion.CASCADE, to='Agenda.agenda')),
            ],
        ),
    ]
