# Generated by Django 5.0.6 on 2024-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoInforme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Archivo', models.FileField(upload_to='construred/informes/')),
                ('TipoInforme', models.ForeignKey(db_column='idTipoInforme', on_delete=django.db.models.deletion.CASCADE, to='TipoInforme.tipoinforme')),
            ],
        ),
    ]
