# Generated by Django 5.0.6 on 2024-05-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyecto', '__first__'),
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(default='Pendiente', max_length=50)),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('Proyecto', models.ForeignKey(db_column='idProyecto', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
                ('Tarea', models.ForeignKey(db_column='idTarea', on_delete=django.db.models.deletion.CASCADE, to='Tarea.tarea')),
            ],
        ),
    ]
