# Generated by Django 5.0.6 on 2024-05-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '__first__'),
        ('TipoMensaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(default='Pendiente', max_length=100)),
                ('FechaHoraMensaje', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('TipoMensaje', models.ForeignKey(db_column='idTipoMensaje', on_delete=django.db.models.deletion.CASCADE, to='TipoMensaje.tipomensaje')),
            ],
        ),
    ]
